### ISSUE TITLE
你好，readme.md里面有几个文件需要申请权限，能把权限开放一下吗？

### ISSUE THREAD

**Issue by qingchenkanlu** [JiChun-Wang/MGRNet#1]
![image](https://user-images.githubusercontent.com/44363924/191735390-22d85956-48d8-495f-8d5a-173bbc2434c9.png)
![image](https://user-images.githubusercontent.com/44363924/191735596-b3b9bbfe-4e80-46e6-a88f-cfd571255e41.png)

**Comment by JiChun-Wang** [comment]
已经开放了。

**Comment by qingchenkanlu** [comment]
你好，再麻烦一下，label_real.py里面有非常多的bug，麻烦您传一下最新的文件

Traceback (most recent call last):
  File "label_real.py", line 151, in <module>
    main(args)
  File "label_real.py", line 117, in main
    R = np.array(annot_pose[k][j]['cam_R_m2c'], dtype=np.float32).reshape(3, 3)
NameError: name 'j' is not defined

Traceback (most recent call last):
  File "label_real.py", line 152, in <module>
    main(args)
  File "label_real.py", line 121, in main
    row_idx, col_idx = labels.nonzero()
ValueError: too many values to unpack (expected 2)

Traceback (most recent call last):
  File "label_real.py", line 152, in <module>
    main(args)
  File "label_real.py", line 128, in main
    correspondences[row_idx, col_idx] = delta_xyz
NameError: name 'correspondences' is not defined
